mystore/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="account/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
]

mystore/mystore/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("account/", include("account.urls", namespace="account")),
    path("account/", include("django.contrib.auth.urls")),
    path("products/", include("products.urls")),
    path("admin/", admin.site.urls),
]

mystore/products/urls.py
from django.urls import path, re_path

from . import views

app_name = "products"

urlpatterns = [
    path("", views.ProductList.as_view(), name="product_list"),
    re_path(r"(?P<pk>\d+)/$", views.ProductDetail.as_view(), name="detail"),
    path("update_item/", views.update_item, name="update_item"),
    path("cart/", views.CartList.as_view(), name="cart_list"),
    path("order/", views.order_save, name="order"),
    path("order_list/", views.OrderList.as_view(), name="order_list"),
    path("wishlist/", views.WishListView.as_view(), name="wishlist"),
    path("update_wishlist/", views.update_wishlist, name="update_wishlist"),
]

mystore/account/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class UserInfo(auth.models.User, auth.models.PermissionsMixin):
    def __str__(self):
        return "@{}".format(self.username)

mystore/products/models.py
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()


class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(max_length=5000)
    description = models.TextField()

    def __str__(self):
        return self.name


class WishList(models.Model):
    user = models.ForeignKey(
        User,
        related_name="user_wishlist",
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.user.username


class Cart(models.Model):
    user = models.ForeignKey(
        User,
        related_name="user_cart",
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="cart_product"
    )
    quantity = models.IntegerField()

    def __str__(self):
        return self.user.username + " " + self.product.name


class Order(models.Model):
    user = models.ForeignKey(
        User,
        related_name="user_order",
        on_delete=models.CASCADE,
    )

    product = models.ManyToManyField(Product)
    order_total = models.DecimalField(max_digits=6, decimal_places=2)
    order_date = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.user.username

mystore/account/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class CreateUserForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Name"
        self.fields["email"].label = "Email address"

mystore/account/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms


class SignUp(CreateView):
    form_class = forms.CreateUserForm
    success_url = reverse_lazy("login")
    template_name = "account/signup.html"

mystore/mystore/views.py
from django.shortcuts import render

from django.views import generic
from products.models import Cart


class HomePage(generic.TemplateView):
    model = Cart
    template_name = "index.html"

mystore/products/views.py
from django.shortcuts import render

from .models import Product, Cart, Order, WishList
from django.views import generic
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
import json
from django.db.models import Sum
from django.db.models import FloatField


class ProductList(generic.ListView):
    model = Product
    template_name = "products/product_list.html"


class CartList(generic.ListView):
    model = Cart
    context_object_name = "cart_list"
    template_name = "products/cart_list.html"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        user = self.request.user
        context["cart_qty"] = Cart.objects.filter(user=user).aggregate(Sum("quantity"))
        context["cart_of_user"] = Cart.objects.filter(user=user)
        total = 0
        for val in context.get("cart_of_user"):
            total += val.quantity * val.product.price
        context["cart_total"] = total
        return context


class ProductDetail(generic.DetailView):
    model = Product


class OrderList(generic.ListView):
    model = Order
    template_name = "products/order_list.html"


class WishListView(generic.ListView):
    model = WishList
    context_object_name = "wish_list"
    template_name = "products/wishlist.html"


@login_required
def update_item(request):

    data = json.loads(request.body)
    product_id = data.get("productId")
    user = request.user
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(product=product, user=user)
        if cart.quantity >= 1:
            cart.quantity = cart.quantity + 1
            cart.save()
    except Cart.DoesNotExist:
        cart = Cart(user=user, product=product, quantity=1)
        cart.save()

    return JsonResponse("item was added ", safe=False)


@login_required
def order_save(request):
    user = request.user
    user_cart = list(Cart.objects.filter(user=user))
    total = 0
    for val in user_cart:
        total += val.quantity * val.product.price
    order_total= total
    order = Order.objects.create(user=user, order_total=total)

    for item in user_cart:
        order.product.add(item.product)
    order.save()
    Cart.objects.filter(user=user).delete()

    return JsonResponse("Order Placed.. ", safe=False)


@login_required
def update_wishlist(request):

    data = json.loads(request.body)
    product_id = data.get("productId")
    user = request.user
    product = Product.objects.get(id=product_id)
    try:
        wishlist = WishList.objects.get(product=product, user=user)
    except WishList.DoesNotExist:
        wishlist = WishList(user=user, product=product)
        wishlist.save()
    return JsonResponse("Order Placed.. ", safe=False)

mystore/products/templates/products/cart_list.html
{% extends "base.html" %}
{% load static %}

{% load multiply %}
{% block content %}
<div class="col-md-8">
    <h1> My Cart</h1>
    <!-- {{ cart_list }} -->
    <div class="cart-table">
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Quantity</th>
                    <th>Unit Price</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>


                {% for cart in cart_list %}
                {% if cart.user == user %}
                <tr>
                    <td>{{ cart.product }}</td>
                    <td><input type="number" name="" value="{{ cart.quantity }}"></td>
                    <td>{{ cart.product.price }}</td>
                    <td class="unit_total">{{ cart.product.price|mul:cart.quantity }}</td>
                </tr>
                {% endif %}



                {% endfor %}
                <tr>
                    <!-- <td><button data-product="{{ product.id }}" data-action="add_wishlist" class="btn btn-warning update-cart">Update Cart</button></td> -->
                    <td><b>Quantity-</b></td>
                    <td>
                        {% for value in cart_qty.values %}
                        {{ value }}
                        {% endfor %}
                    </td>
                    <td><b>Cart Total-</b></td>
                    <td class="total">
                        {{ cart_total }}
                    </td>
                </tr>


            </tbody>

        </table>

        <div>
            <a href="{% url 'products:order' %}" class="btn btn-primary btn-lg">Order</a>
        </div>

    </div>
</div>
{% endblock %}

mystore/products/templates/products/order.html
Random Text

mystore/products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}


{% block products_contents %}
<div class="container mt-5 mb-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-10">
            <div class="row p-2 bg-white border rounded">
                <div class="col-md-3 mt-1"> <a href="{% url 'products:detail' pk=product.pk %}"><img class="img-fluid img-responsive rounded product-image" src="{% static 'img/' %}{{ product.image }}"></a></div>
                <div class="col-md-6 mt-1">
                    <a href="{% url 'products:detail' pk=product.pk %}">
                        <h5>{{ product.name }}</h5>
                    </a>

                    <p class="text-justify text-truncate para mb-0">{{ product.description }}<br><br></p>
                </div>
                <div class="align-items-center align-content-center col-md-3 border-left mt-1">
                    <div class="d-flex flex-row align-items-center">
                        <h4 class="mr-1">{{ product.price }}</h4><span class="strike-text"></span>
                    </div>
                    <!-- <h6 class="text-success">Free shipping</h6> -->
                    <div class="d-flex flex-column mt-4"><button class="btn btn-primary btn-sm update-cart" data-product="{{ product.id }}" data-action="add_cart" type="button">Add to Cart</button><button class="btn btn-outline-primary btn-sm mt-2" type="button">Add to wishlist</button></div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

mystore/products/templates/products/product_list.html
{% extends "base.html" %}
{% load static %}


{% block products_contents %}
<!-- <div class="col-md-8"> -->
{% for product in product_list %}
<div class="container mt-5 mb-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-10">
            <div class="row p-2 bg-white border rounded">
                <div class="col-md-3 mt-1"> <a href="{% url 'products:detail' pk=product.pk %}"><img class="img-fluid img-responsive rounded product-image" src="{% static 'img/' %}{{ product.image }}"></a></div>
                <div class="col-md-6 mt-1">
                    <a href="{% url 'products:detail' pk=product.pk %}">
                        <h5>{{ product.name }}</h5>
                    </a>

                    <p class="text-justify text-truncate para mb-0">{{ product.description }}<br><br></p>
                </div>
                <div class="align-items-center align-content-center col-md-3 border-left mt-1">
                    <div class="d-flex flex-row align-items-center">
                        <h4 class="mr-1">{{ product.price }}</h4><span class="strike-text"></span>
                    </div>
                    <!-- <h6 class="text-success">Free shipping</h6> -->
                    <div class="d-flex flex-column mt-4">
                        <button class="btn btn-primary btn-sm update-cart" data-product="{{ product.id }}" data-action="add_cart" type="button">Add to Cart</button>
                        <button class="btn btn-outline-primary btn-sm mt-2 update-wishlist" data-product="{{ product.id }}" data-action="update_wishlist" type="button">Add to wishlist</button>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


{% endfor %}
<!-- </div> -->
{% endblock %}

mystore/products/templates/products/wishlist.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="col-md-8">
    <h1> My Wishlist</h1>

    <div class="cart-table">
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th>Item</th>

                    <th>Price</th>

                </tr>
            </thead>
            <tbody>


                {% for wishlist in wish_list %}
                {% if wishlist.user == user %}
                <tr>
                    <td>{{ wishlist.product.name }}</td>

                    <td>{{ wishlist.product.price }}</td>

                </tr>
                {% endif %}



                {% endfor %}

            </tbody>

        </table>
    </div>
</div>
{% endblock %}

mystore/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>My Store</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png'%}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png'%}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Poppins:300,400,500,700" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/venobox/venobox.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css'%}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'mystore/css/style.css'%}" rel="stylesheet">
    <link href="{% static 'mystore/css/master.css'%}" rel="stylesheet">

    <!-- =======================================================
  * Template Name: Regna - v2.2.1
  * Template URL: https://bootstrapmade.com/regna-bootstrap-onepage-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->

    <script type="text/javascript">
        var user = '{{request.user}}';

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
    </script>

</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header-transparent">
        <div class="container">

            <div id="logo" class="pull-left">
                <a href="{% url 'products:product_list' %}"><img src="{% static 'assets/img/logo.png' %}" alt=""></a>
                <!-- Uncomment below if you prefer to use a text logo -->
                <!--<h1><a href="#hero">Regna</a></h1>-->
            </div>

            <nav id="nav-menu-container">
                <ul class="nav-menu">

                    {% if user.is_authenticated %}

                    <li><a href="{% url 'index' %}">Welcome {{ user.username }}!</a></li>
                    <li><a href="{% url 'products:product_list' %}" class="menu-active">Products</a></li>
                    <li><a href="{% url 'products:cart_list' %}"><span style="color: red">{{ user.user_cart.count }} </span>Cart</a></li>
                    <li><a href="{% url 'products:wishlist' %}">Wishlist</a></li>
                    <li><a href="{% url 'account:logout' %}">Log out</a></li>


                    {% else %}



                    <li class="menu-active"><a href="{% url 'products:product_list' %}">Products</a></li>
                    <li><a href="{% url 'account:login' %}">Login</a></li>
                    <li><a href="{% url 'account:signup' %}">Sign Up</a></li>
                    {% endif %}
                    <!--   <li><a href="#portfolio">Portfolio</a></li>
          <li><a href="#team">Team</a></li> -->
                    <!-- <li class="menu-has-children"><a href="">Drop Down</a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="menu-has-children"><a href="#">Drop Down 2</a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
              <li><a href="#">Drop Down 5</a></li>
            </ul>
          </li> -->

                </ul>
            </nav><!-- #nav-menu-container -->
        </div>
    </header><!-- End Header -->
    <!-- ======= Hero Section ======= -->
    <!-- <section id="hero"> -->
    <!--  <div class="hero-container" >
      <h1>Welcome to REGNA</h1>
      <h2>We are team of talented designers making websites with Bootstrap</h2>
      <a href="{% url 'products:product_list' %}" class="btn-get-started">Get Started</a>
    </div> -->
    <!-- </section> -->
    <!-- End Hero Section -->
    <main id="main">
        <!-- End Contact Section -->
        <!--  <div class="container jumbotron"> -->
        {% block content %}

        {% endblock %}

        <!-- </div> -->
        {% block cart_contents %}
        <!--  <div class="container mystore-cart-content">
         

        </div> -->
        {% endblock %}


        <div class="container mystorecontent">
            {% block products_contents %}

            {% endblock %}

        </div>
    </main>

    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
            <div class="container">

            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong>@MyStoreRegna</strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!--
        All the links in the footer should remain intact.
        You can delete the links only if you purchased the pro version.
        Licensing information: https://bootstrapmade.com/license/
        Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Regna
      -->
                Designed by <a href="#">@Shubham Varfa</a>
            </div>
        </div>
    </footer><!-- End Footer -->


    <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'assets/vendor/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/superfish/superfish.min.js' %}"></script>
    <script src="{% static 'assets/vendor/hoverIntent/hoverIntent.js' %}"></script>
    <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="{% static 'js/cart.js'%}" type="text/javascript"></script>

</body>

</html>

mystore/templates/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>My Store</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png'%}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png'%}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Poppins:300,400,500,700" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/venobox/venobox.css'%}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css'%}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'mystore/css/style.css'%}" rel="stylesheet">
    <link href="{% static 'mystore/css/master.css'%}" rel="stylesheet">

    <!-- =======================================================
  * Template Name: Regna - v2.2.1
  * Template URL: https://bootstrapmade.com/regna-bootstrap-onepage-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->

    <script type="text/javascript">
        var user = '{{request.user}}';

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
    </script>

</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header-transparent">
        <div class="container">

            <div id="logo" class="pull-left">
                <a href="{% url 'products:product_list' %}"><img src="{% static 'assets/img/logo.png' %}" alt=""></a>
                <!-- Uncomment below if you prefer to use a text logo -->
                <!--<h1><a href="#hero">Regna</a></h1>-->
            </div>

            <nav id="nav-menu-container">
                <ul class="nav-menu">

                    {% if user.is_authenticated %}

                    <li><a href="#">Welcome {{ user.username }}!</a></li>
                    <li><a href="{% url 'products:product_list' %}" class="menu-active">Products</a></li>
                    <li><a href="{% url 'products:cart_list' %}"><span style="color: red">{{ user.user_cart.count }} </span>Cart</a></li>
                    <li><a href="#">Wishlist</a></li>
                    <li><a href="{% url 'account:logout' %}">Log out</a></li>


                    {% else %}



                    <li class="menu-active"><a href="{% url 'products:product_list' %}">Products</a></li>
                    <li><a href="{% url 'account:login' %}">Login</a></li>
                    <li><a href="{% url 'account:signup' %}">Sign Up</a></li>
                    {% endif %}
                    <!--   <li><a href="#portfolio">Portfolio</a></li>
          <li><a href="#team">Team</a></li> -->
                    <!-- <li class="menu-has-children"><a href="">Drop Down</a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="menu-has-children"><a href="#">Drop Down 2</a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
              <li><a href="#">Drop Down 5</a></li>
            </ul>
          </li> -->

                </ul>
            </nav><!-- #nav-menu-container -->
        </div>
    </header><!-- End Header -->
    <!-- ======= Hero Section ======= -->
    {% block hero %}
    <section id="hero">
        <div class="hero-container">
            <h1>Welcome to REGNA</h1>
            <h2>We're constantly getting exciting new products. Here are a few of our favorites on our shelves right now</h2>
            <a href="{% url 'products:product_list' %}" class="btn-get-started">Get Started</a>
        </div>
    </section>
    {% endblock %}
    <!-- End Hero Section -->
    <main id="main">
        <!-- End Contact Section -->
        <!--  <div class="container jumbotron"> -->
        {% block content %}

        {% endblock %}

        <!-- </div> -->
        {% block cart_contents %}
        <!--  <div class="container mystore-cart-content">
         

        </div> -->
        {% endblock %}


        <div class="container mystorecontent">
            {% block products_contents %}

            {% endblock %}

        </div>
    </main>

    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
            <div class="container">

            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong>@MyStoreRegna</strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!--
        All the links in the footer should remain intact.
        You can delete the links only if you purchased the pro version.
        Licensing information: https://bootstrapmade.com/license/
        Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Regna
      -->
                Designed by <a href="#">@Shubham Varfa</a>
            </div>
        </div>
    </footer><!-- End Footer -->


    <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'assets/vendor/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/superfish/superfish.min.js' %}"></script>
    <script src="{% static 'assets/vendor/hoverIntent/hoverIntent.js' %}"></script>
    <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="{% static 'js/cart.js'%}" type="text/javascript"></script>

</body>

</html>